#!/bin/bash
set -euo pipefail

# Non-login SSH sessions do not load root's Nix profile.  PM2 passes this PATH
# to Hydro, whose node launcher uses /usr/bin/env.
export PATH="/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

source_dir="${SOURCE_DIR:-/opt/noi-linux-contest-system/current-source/hydro-plugin-orchestrator}"
: "${EXPECTED_SOURCE_RELEASE:?set EXPECTED_SOURCE_RELEASE to revision-manifestprefix from the verified plan}"
external_transaction="${EXTERNAL_INSTALL_TRANSACTION:-0}"
addon_dir=/root/.hydro/addons/orchestrator-submit
addon_file=/root/.hydro/addon.json
token_file=/root/.hydro/orchestrator-token
plugin_env=/root/.hydro/orchestrator-plugin.env
pm2="${PM2_BIN:-}"
node="${NODE_BIN:-}"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
backup=/root/noi-backups/hydro-addon-${timestamp}

if [[ "${EUID}" -ne 0 ]]; then
  echo "must run as root" >&2
  exit 1
fi
if [[ "${external_transaction}" != 0 && "${external_transaction}" != 1 ]]; then
  echo "EXTERNAL_INSTALL_TRANSACTION must be 0 or 1" >&2
  exit 1
fi
if [[ ! "${EXPECTED_SOURCE_RELEASE}" =~ ^[a-f0-9]{40}-[a-f0-9]{12}$ ]] \
    || [[ ! "${source_dir}" =~ ^/opt/noi-linux-contest-system/(current-source|source-releases/[a-f0-9]{40}-[a-f0-9]{12})/hydro-plugin-orchestrator$ ]] \
    || [[ ! -d "${source_dir}" ]] || [[ -L "${source_dir}" ]]; then
  echo "SOURCE_DIR must be the trusted current-source plugin or an exact source release plugin directory" >&2
  exit 1
fi
resolved_source_dir="$(realpath -e -- "${source_dir}")"
expected_source_dir="/opt/noi-linux-contest-system/source-releases/${EXPECTED_SOURCE_RELEASE}/hydro-plugin-orchestrator"
if [[ "${resolved_source_dir}" != "${expected_source_dir}" ]]; then
  echo "SOURCE_DIR does not resolve to EXPECTED_SOURCE_RELEASE" >&2
  exit 1
fi
source_dir="${resolved_source_dir}"

if [[ -z "${pm2}" ]]; then
  pm2="$(find /nix/store -type f -path '*/pm2/bin/pm2' 2>/dev/null \
    | sort | tail -n1)"
fi
if [[ -z "${node}" ]]; then
  for candidate in /root/.nix-profile/bin/node /usr/local/bin/node; do
    if [[ -x "${candidate}" ]]; then
      node="${candidate}"
      break
    fi
  done
fi
test -x "${pm2}"
test -x "${node}"
test -s "${source_dir}/index.js"
test -s "${source_dir}/package.json"
python3 - "${source_dir}" <<'PY'
from pathlib import Path
import os, stat, sys

root = Path(sys.argv[1])
expected = {
    "index.js", "package.json", "tests",
    "tests/orchestrator-materials.test.js",
    "tests/orchestrator-notify.test.js",
    "tests/orchestrator-problem-fileio.test.js",
    "tests/orchestrator-submit.test.js",
}
observed = set()
for path in root.rglob("*"):
    relative = path.relative_to(root).as_posix()
    info = os.lstat(path)
    if stat.S_ISLNK(info.st_mode) or relative not in expected:
        raise SystemExit("plugin source tree contains an unexpected entry")
    if path.is_dir():
        if relative != "tests":
            raise SystemExit("plugin source tree contains an unexpected directory")
    elif not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
        raise SystemExit("plugin source file metadata is unsafe")
    observed.add(relative)
if observed != expected:
    raise SystemExit("plugin source tree is incomplete")
PY
test -s "${addon_file}"
test -s "${token_file}"
test -s "${plugin_env}"
if [[ "$(stat -c '%a' "${plugin_env}")" != 600 ]]; then
  echo "${plugin_env} must have mode 0600" >&2
  exit 1
fi
# This file is generated by install-hydro-host.sh, owned by root and mode 0600.
# Export it explicitly so PM2 persists the same paths/allowlist across restarts.
# PM2 merges --update-env and cannot remove a key merely because it is absent
# from the caller.  Start from an exact prefix-free process environment; the
# trusted root-only env file below is the sole source of desired values.
unset ORCHESTRATOR_TOKEN
unset ORCHESTRATOR_TOKEN_FILE \
  ORCHESTRATOR_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE \
  ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE \
  ORCHESTRATOR_MATERIAL_IDEMPOTENCY_FILE \
  ORCHESTRATOR_MATERIAL_MAX_BYTES \
  ORCHESTRATOR_NOTIFY_ALLOWED_HTTPS_HOSTS
while IFS= read -r inherited; do
  unset -v "${inherited}"
done < <(compgen -A variable ORCHESTRATOR_ || true)
set -a
# shellcheck disable=SC1090
source "${plugin_env}"
set +a
for required in \
  ORCHESTRATOR_TOKEN_FILE \
  ORCHESTRATOR_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE \
  ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE \
  ORCHESTRATOR_MATERIAL_IDEMPOTENCY_FILE \
  ORCHESTRATOR_MATERIAL_MAX_BYTES \
  ORCHESTRATOR_NOTIFY_ALLOWED_HTTPS_HOSTS; do
  if [[ -z "${!required:-}" ]]; then
    echo "missing ${required} in ${plugin_env}" >&2
    exit 1
  fi
done
install -d -m 0700 "$(dirname "${ORCHESTRATOR_IDEMPOTENCY_FILE}")"
if [[ "${external_transaction}" = 1 ]]; then
  "${node}" --check "${source_dir}/index.js" >/dev/null
  "${node}" --test "${source_dir}"/tests/*.test.js >/dev/null
else
  "${node}" --check "${source_dir}/index.js"
  "${node}" --test "${source_dir}"/tests/*.test.js
fi
if [[ "$(wc -c < "${token_file}")" -lt 33 ]]; then
  echo "orchestrator token is too short" >&2
  exit 1
fi

if [[ "${external_transaction}" = 0 ]]; then
  install -d -m 0700 "${backup}"
  cp -a "${addon_file}" "${backup}/addon.json"
  if [[ -d "${addon_dir}" ]]; then
    cp -a "${addon_dir}" "${backup}/orchestrator-submit"
  fi
fi

wait_for_hydro() {
  local timeout_seconds="$1"
  for _ in $(seq 1 "${timeout_seconds}"); do
    if curl -fsS http://127.0.0.1:8888/ >/dev/null; then
      return 0
    fi
    sleep 1
  done
  return 1
}

rollback() {
  local legacy_token
  echo "rolling back Hydro addon" >&2
  cp -a "${backup}/addon.json" "${addon_file}"
  if [[ -d "${backup}/orchestrator-submit" ]]; then
    rm -rf "${addon_dir}"
    cp -a "${backup}/orchestrator-submit" "${addon_dir}"
  else
    rm -rf "${addon_dir}"
  fi
  legacy_token="$(tr -d '\r\n' < "${token_file}")"
  if ! ORCHESTRATOR_TOKEN="${legacy_token}" \
    "${pm2}" restart hydrooj --update-env >/dev/null; then
    echo "rollback PM2 restart failed; waiting for Hydro recovery" >&2
  fi
  "${pm2}" save --force >/dev/null || true
  if ! wait_for_hydro 120; then
    echo "Hydro did not recover within 120 seconds after rollback" >&2
    return 1
  fi
}
if [[ "${external_transaction}" = 0 ]]; then
  trap 'rollback' ERR
fi

install -d -m 0755 "${addon_dir}"
install -m 0644 "${source_dir}/index.js" "${addon_dir}/index.js"
install -m 0644 "${source_dir}/package.json" "${addon_dir}/package.json"

python3 - "${addon_file}" "${addon_dir}" <<'PY'
import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
addon = sys.argv[2]
items = json.loads(path.read_text(encoding='utf-8'))
if not isinstance(items, list):
    raise ValueError('addon.json must contain an array')
if addon not in items:
    items.append(addon)
temporary = path.with_suffix('.json.tmp')
temporary.write_text(json.dumps(items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
temporary.replace(path)
PY

"${pm2}" restart hydrooj --update-env >/dev/null
"${pm2}" save --force >/dev/null
wait_for_hydro 60

timeout --kill-after=5s 20s "${pm2}" jlist --silent | python3 -c '
import json, os, sys
rows=json.load(sys.stdin)
matches=[row for row in rows if row.get("name")=="hydrooj"]
if len(matches)!=1 or not isinstance(matches[0].get("pm2_env"),dict):
    raise SystemExit("PM2 does not contain exactly one Hydro definition")
definition=matches[0]["pm2_env"]
nested=definition.get("env")
if not isinstance(nested,dict):
    raise SystemExit("PM2 Hydro nested environment is absent")
desired={key:value for key,value in os.environ.items() if key.startswith("ORCHESTRATOR_")}
if not desired or "ORCHESTRATOR_TOKEN" in desired:
    raise SystemExit("desired ORCHESTRATOR environment is unsafe")
nested_prefix={key:value for key,value in nested.items() if key.startswith("ORCHESTRATOR_")}
top_prefix={key:value for key,value in definition.items() if key.startswith("ORCHESTRATOR_")}
if nested_prefix!=desired:
    raise SystemExit("PM2 Hydro nested ORCHESTRATOR environment differs")
if not set(top_prefix).issubset(desired) or any(desired[key]!=value for key,value in top_prefix.items()):
    raise SystemExit("PM2 Hydro top-level ORCHESTRATOR environment differs")
'

for state_file in \
  "${ORCHESTRATOR_IDEMPOTENCY_FILE}" \
  "${ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE}" \
  "${ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE}" \
  "${ORCHESTRATOR_MATERIAL_IDEMPOTENCY_FILE}"; do
  test -s "${state_file}"
  if [[ "$(stat -c '%a' "${state_file}")" != 600 ]]; then
    echo "plugin state file must have mode 0600: ${state_file}" >&2
    exit 1
  fi
  if [[ ! -w "${state_file}" ]]; then
    echo "plugin state file is not writable: ${state_file}" >&2
    exit 1
  fi
done

token="$(tr -d '\r\n' < "${token_file}")"
for endpoint in '' '/notify' '/problem-fileio' '/materials'; do
  body="/tmp/noi-addon-check-${RANDOM}.body"
  status="$(curl -sS -o "${body}" -w '%{http_code}' \
    -X POST -H "X-Orchestrator-Token: ${token}" \
    --data 'tid=invalid&uid=1&pid=invalid&code=x' \
    "http://127.0.0.1:8888/orchestrator/submit${endpoint}")"
  rm -f "${body}"
  case "${status}" in
    400|409|413|422)
      ;;
    *)
      echo "orchestrator route probe returned an unexpected status: ${endpoint:-/} (HTTP ${status})" >&2
      exit 1
      ;;
  esac
done

if [[ "${external_transaction}" = 0 ]]; then
  trap - ERR
  echo "hydro_addon_enabled submit_notify_problem_fileio_materials=ok backup=${backup} transaction=standalone"
else
  python3 - "${EXPECTED_SOURCE_RELEASE}" <<'PY'
import json,sys
print(json.dumps({"status":"verified","transaction":"external","source_release":sys.argv[1],
 "hydro":"online","routes":"submit-notify-problem-fileio-materials","other_pm2_mutations":0},
 sort_keys=True,separators=(",",":")))
PY
fi
