#!/bin/bash
set -euo pipefail

# Non-login SSH sessions do not load root's Nix profile.  PM2 passes this PATH
# to Hydro, whose node launcher uses /usr/bin/env.
export PATH="/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

source_dir=/opt/noi-linux-contest-system/hydro-plugin-orchestrator
addon_dir=/root/.hydro/addons/orchestrator-submit
addon_file=/root/.hydro/addon.json
token_file=/root/.hydro/orchestrator-token
plugin_env=/root/.hydro/orchestrator-plugin.env
pm2="${PM2_BIN:-}"
node="${NODE_BIN:-}"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
backup=/root/noi-backups/hydro-addon-${timestamp}

if [[ "${EUID}" -ne 0 ]]; then
  echo "must run as root" >&2
  exit 1
fi

if [[ -z "${pm2}" ]]; then
  pm2="$(find /nix/store -type f -path '*/pm2/bin/pm2' 2>/dev/null \
    | sort | tail -n1)"
fi
if [[ -z "${node}" ]]; then
  for candidate in /root/.nix-profile/bin/node /usr/local/bin/node; do
    if [[ -x "${candidate}" ]]; then
      node="${candidate}"
      break
    fi
  done
fi
test -x "${pm2}"
test -x "${node}"
test -s "${source_dir}/index.js"
test -s "${source_dir}/package.json"
test -s "${addon_file}"
test -s "${token_file}"
test -s "${plugin_env}"
if [[ "$(stat -c '%a' "${plugin_env}")" != 600 ]]; then
  echo "${plugin_env} must have mode 0600" >&2
  exit 1
fi
# This file is generated by install-hydro-host.sh, owned by root and mode 0600.
# Export it explicitly so PM2 persists the same paths/allowlist across restarts.
unset ORCHESTRATOR_TOKEN
unset ORCHESTRATOR_TOKEN_FILE \
  ORCHESTRATOR_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE \
  ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFY_ALLOWED_HTTPS_HOSTS
set -a
# shellcheck disable=SC1090
source "${plugin_env}"
set +a
for required in \
  ORCHESTRATOR_TOKEN_FILE \
  ORCHESTRATOR_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE \
  ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE \
  ORCHESTRATOR_NOTIFY_ALLOWED_HTTPS_HOSTS; do
  if [[ -z "${!required:-}" ]]; then
    echo "missing ${required} in ${plugin_env}" >&2
    exit 1
  fi
done
install -d -m 0700 "$(dirname "${ORCHESTRATOR_IDEMPOTENCY_FILE}")"
"${node}" --check "${source_dir}/index.js"
"${node}" --test "${source_dir}"/tests/*.test.js
if [[ "$(wc -c < "${token_file}")" -lt 33 ]]; then
  echo "orchestrator token is too short" >&2
  exit 1
fi

install -d -m 0700 "${backup}"
cp -a "${addon_file}" "${backup}/addon.json"
if [[ -d "${addon_dir}" ]]; then
  cp -a "${addon_dir}" "${backup}/orchestrator-submit"
fi

wait_for_hydro() {
  local timeout_seconds="$1"
  for _ in $(seq 1 "${timeout_seconds}"); do
    if curl -fsS http://127.0.0.1:8888/ >/dev/null; then
      return 0
    fi
    sleep 1
  done
  return 1
}

rollback() {
  local legacy_token
  echo "rolling back Hydro addon" >&2
  cp -a "${backup}/addon.json" "${addon_file}"
  if [[ -d "${backup}/orchestrator-submit" ]]; then
    rm -rf "${addon_dir}"
    cp -a "${backup}/orchestrator-submit" "${addon_dir}"
  else
    rm -rf "${addon_dir}"
  fi
  legacy_token="$(tr -d '\r\n' < "${token_file}")"
  if ! ORCHESTRATOR_TOKEN="${legacy_token}" \
    "${pm2}" restart hydrooj --update-env >/dev/null; then
    echo "rollback PM2 restart failed; waiting for Hydro recovery" >&2
  fi
  "${pm2}" save --force >/dev/null || true
  if ! wait_for_hydro 120; then
    echo "Hydro did not recover within 120 seconds after rollback" >&2
    return 1
  fi
}
trap 'rollback' ERR

install -d -m 0755 "${addon_dir}"
install -m 0644 "${source_dir}/index.js" "${addon_dir}/index.js"
install -m 0644 "${source_dir}/package.json" "${addon_dir}/package.json"

python3 - "${addon_file}" "${addon_dir}" <<'PY'
import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
addon = sys.argv[2]
items = json.loads(path.read_text(encoding='utf-8'))
if not isinstance(items, list):
    raise ValueError('addon.json must contain an array')
if addon not in items:
    items.append(addon)
temporary = path.with_suffix('.json.tmp')
temporary.write_text(json.dumps(items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
temporary.replace(path)
PY

"${pm2}" restart hydrooj --update-env >/dev/null
"${pm2}" save --force >/dev/null
wait_for_hydro 60

for state_file in \
  "${ORCHESTRATOR_IDEMPOTENCY_FILE}" \
  "${ORCHESTRATOR_NOTIFICATION_IDEMPOTENCY_FILE}" \
  "${ORCHESTRATOR_PROBLEM_DRAFT_IDEMPOTENCY_FILE}"; do
  test -s "${state_file}"
  if [[ "$(stat -c '%a' "${state_file}")" != 600 ]]; then
    echo "plugin state file must have mode 0600: ${state_file}" >&2
    exit 1
  fi
  if [[ ! -w "${state_file}" ]]; then
    echo "plugin state file is not writable: ${state_file}" >&2
    exit 1
  fi
done

token="$(tr -d '\r\n' < "${token_file}")"
for endpoint in '' '/notify' '/problem-fileio'; do
  body="/tmp/noi-addon-check-${RANDOM}.body"
  status="$(curl -sS -o "${body}" -w '%{http_code}' \
    -X POST -H "X-Orchestrator-Token: ${token}" \
    --data 'tid=invalid&uid=1&pid=invalid&code=x' \
    "http://127.0.0.1:8888/orchestrator/submit${endpoint}")"
  rm -f "${body}"
  case "${status}" in
    400|409|413|422)
      ;;
    *)
      echo "orchestrator route probe returned an unexpected status: ${endpoint:-/} (HTTP ${status})" >&2
      exit 1
      ;;
  esac
done

trap - ERR
echo "hydro_addon_enabled submit_notify_problem_fileio=ok backup=${backup}"
