"""Update the stable public Caddy frontend for a dynamic contest ECS IP."""
from __future__ import annotations

import ipaddress
from pathlib import Path
import re
import threading

import requests

_DOMAIN = re.compile(r"^[A-Za-z0-9.-]+$")


class NullFrontend:
    def enable(self, host: str, port: int) -> None:
        return None

    def disable(self) -> None:
        return None


class CaddyFrontend:
    def __init__(self, cfg: dict):
        self.domain = str(cfg["domain"]).strip().lower()
        if not _DOMAIN.fullmatch(self.domain):
            raise ValueError("frontend_proxy.domain 格式无效")
        self.snippet_path = Path(cfg["snippet_path"])
        self.caddyfile_path = Path(cfg["caddyfile_path"])
        self.admin_url = str(cfg.get("admin_url", "http://127.0.0.1:2019")).rstrip(
            "/"
        )
        self.orchestrator_upstream = str(
            cfg.get("orchestrator_upstream", "http://127.0.0.1:8600")
        )
        self._lock = threading.Lock()

    def _render(self, desktop_upstream: str | None) -> str:
        if desktop_upstream:
            # The contest ECS may reject requests whose Host names the public
            # exam domain (Aliyun returns a Beaver 403 before nginx).  Send the
            # validated IP upstream as Host while retaining the original path
            # and Caddy's normal WebSocket forwarding behavior.
            desktop = (
                f"reverse_proxy {desktop_upstream} {{\n"
                "            header_up Host {upstream_hostport}\n"
                "            header_down Location ^http://[^/]+ https://{http.request.host}\n"
                "        }"
            )
        else:
            desktop = 'respond "比赛桌面尚未开放" 503'
        return f"""# Generated by NOI orchestrator. Do not edit while it is running.
{self.domain} {{
    encode zstd gzip
    log {{
        output file /data/noi-exam.access.log {{
            roll_size 200mb
            roll_keep_for 168h
        }}
        format json
    }}
    @desktop path /s/*
    handle @desktop {{
        {desktop}
    }}
    handle {{
        reverse_proxy {self.orchestrator_upstream}
    }}
}}
"""

    def _write_and_reload(self, content: str) -> None:
        self.snippet_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.snippet_path.with_suffix(self.snippet_path.suffix + ".tmp")
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(self.snippet_path)
        caddyfile = self.caddyfile_path.read_bytes()
        response = requests.post(
            f"{self.admin_url}/load",
            data=caddyfile,
            headers={"Content-Type": "text/caddyfile"},
            timeout=15,
        )
        if response.status_code >= 300:
            raise RuntimeError(
                f"Caddy reload failed: HTTP {response.status_code} {response.text[:500]}"
            )

    def enable(self, host: str, port: int) -> None:
        ipaddress.ip_address(host)
        if not 1 <= int(port) <= 65535:
            raise ValueError("frontend upstream port is invalid")
        with self._lock:
            self._write_and_reload(self._render(f"http://{host}:{int(port)}"))

    def disable(self) -> None:
        with self._lock:
            self._write_and_reload(self._render(None))


def make_frontend(cfg: dict | None):
    cfg = cfg or {}
    provider = str(cfg.get("provider", "none")).lower()
    if provider in {"", "none"}:
        return NullFrontend()
    if provider == "caddy":
        return CaddyFrontend(cfg)
    raise ValueError(f"unsupported frontend_proxy.provider: {provider}")
