#!/usr/bin/env python3
"""Publish or roll back the closed V1 Caddy frontend as one owned phase."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import stat
import sys
import tempfile

from commit_v1_caddy_config import (
    Admin, CaddyCommitError, adapt, canonical as caddy_canonical, commit, get_live,
    json_value, restore,
)
from verify_v1_install_backup import safe_directory, safe_file, validate_manifest


HEX64 = re.compile(r"^[a-f0-9]{64}$")
DOMAIN = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$")
MARKER = "# noi-orchestrator-private-submit"


class ClosedFrontendError(RuntimeError):
    pass


def _domain(value: str, label: str) -> str:
    value = value.strip().lower()
    if not DOMAIN.fullmatch(value) or "." not in value or ".." in value:
        raise ClosedFrontendError(f"{label} differs")
    return value


def _upstream(value: str) -> str:
    if value != "http://127.0.0.1:8600":
        raise ClosedFrontendError("orchestrator upstream differs")
    return value


def render_closed(domain: str, upstream: str) -> bytes:
    return f'''# Generated by NOI orchestrator. Do not edit while it is running.
{domain} {{
    encode zstd gzip
    log {{
        output file /data/noi-exam.access.log {{
            roll_size 200mb
            roll_keep_for 168h
        }}
        format json
    }}
    @desktop path /s/*
    handle @desktop {{
        respond "比赛桌面尚未开放" 503
    }}
    handle {{
        reverse_proxy {upstream}
    }}
}}
'''.encode("utf-8")


def harden_caddyfile(raw: bytes, hydro_domain: str, snippet: Path) -> bytes:
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ClosedFrontendError("Caddyfile is not UTF-8") from exc
    lines = text.splitlines(keepends=True)
    targets = (":80", hydro_domain)
    found: set[str] = set()
    insertions: list[tuple[int, list[str]]] = []
    depth = 0
    for index, line in enumerate(lines):
        stripped = line.strip()
        if depth == 0:
            for target in targets:
                if stripped != f"{target} {{":
                    continue
                found.add(target); block_depth = 0; end = index
                for end in range(index, len(lines)):
                    block_depth += lines[end].count("{") - lines[end].count("}")
                    if block_depth == 0:
                        break
                block = "".join(lines[index:end + 1])
                if MARKER not in block:
                    indent = line[:len(line) - len(line.lstrip())] + "  "
                    insertions.append((index + 1, [
                        f"{indent}{MARKER}\n",
                        f"{indent}handle /orchestrator/submit* {{\n",
                        f"{indent}  respond 404\n",
                        f"{indent}}}\n",
                    ]))
        depth += line.count("{") - line.count("}")
    missing = set(targets) - found
    if missing:
        raise ClosedFrontendError("Caddy site block differs")
    for index, content in reversed(insertions):
        lines[index:index] = content
    snippet_text = snippet.as_posix()
    import_line = f"import {snippet_text}"
    matches = [line for line in lines if line.strip() == import_line]
    if len(matches) > 1:
        raise ClosedFrontendError("closed frontend import is duplicated")
    if not matches:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        lines.extend(["\n", import_line + "\n"])
    desired = "".join(lines).encode("utf-8")
    # A second transform must be byte-idempotent.
    if desired != _harden_once(desired, hydro_domain, snippet):
        raise ClosedFrontendError("Caddy transform is not idempotent")
    return desired


def _harden_once(raw: bytes, hydro_domain: str, snippet: Path) -> bytes:
    text = raw.decode("utf-8"); lines = text.splitlines(keepends=True)
    for target in (":80", hydro_domain):
        depth = 0; blocks = []
        for index, line in enumerate(lines):
            if depth == 0 and line.strip() == f"{target} {{": blocks.append(index)
            depth += line.count("{") - line.count("}")
        if len(blocks) != 1:
            raise ClosedFrontendError("Caddy site block count differs")
        start = blocks[0]; block_depth = 0; end = start
        for end in range(start, len(lines)):
            block_depth += lines[end].count("{") - lines[end].count("}")
            if block_depth == 0: break
        block = "".join(lines[start:end + 1])
        rule = re.compile(
            r"(?m)^\s*# noi-orchestrator-private-submit\s*$\n"
            r"^\s*handle /orchestrator/submit\* \{\s*$\n"
            r"^\s*respond 404\s*$\n^\s*\}\s*$"
        )
        if len(rule.findall(block)) != 1:
            raise ClosedFrontendError("Hydro submit hardening rule differs")
    if sum(line.strip() == f"import {snippet.as_posix()}" for line in lines) != 1:
        raise ClosedFrontendError("closed frontend import count differs")
    if text.count(MARKER) != 2:
        raise ClosedFrontendError("Hydro submit hardening marker count differs")
    return raw


def _atomic(path: Path, raw: bytes, mode: int) -> None:
    parent = path.parent.resolve(strict=True)
    metadata = os.lstat(parent)
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise ClosedFrontendError("frontend target parent is unsafe")
    if platform.system().lower() == "linux" and (
            metadata.st_uid != 0 or stat.S_IMODE(metadata.st_mode) & 0o022):
        raise ClosedFrontendError("frontend target parent is writable")
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.v1-", dir=parent)
    try:
        if hasattr(os, "fchmod"): os.fchmod(descriptor, mode)
        else: os.chmod(temporary, mode)
        with os.fdopen(descriptor, "wb", closefd=True) as output:
            descriptor = -1; output.write(raw); output.flush(); os.fsync(output.fileno())
        os.replace(temporary, path)
        if platform.system().lower() == "linux":
            directory = os.open(parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
            try: os.fsync(directory)
            finally: os.close(directory)
    finally:
        if descriptor >= 0: os.close(descriptor)
        if os.path.lexists(temporary): os.unlink(temporary)


def _current(path: Path, maximum: int = 32 * 1024 * 1024) -> tuple[bytes, int]:
    raw, metadata = safe_file(path, maximum=maximum)
    return raw, stat.S_IMODE(metadata.st_mode)


def _optional_current(path: Path, maximum: int = 32 * 1024 * 1024) -> tuple[bytes, int] | None:
    if not os.path.lexists(path): return None
    return _current(path, maximum)


def _remove_exact(path: Path, expected: bytes) -> None:
    current = _optional_current(path)
    if current is None: return
    if current[0] != expected:
        raise ClosedFrontendError("frontend snippet changed outside this transaction")
    metadata = os.lstat(path)
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
        raise ClosedFrontendError("frontend snippet metadata is unsafe")
    os.unlink(path)
    if platform.system().lower() == "linux":
        descriptor = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try: os.fsync(descriptor)
        finally: os.close(descriptor)


def _inputs(backup: Path, plan_id: str, manifest_sha256: str):
    root = safe_directory(backup)
    manifest_raw, _ = safe_file(root / "backup-manifest.json", maximum=4 * 1024 * 1024)
    if hashlib.sha256(manifest_raw).hexdigest() != manifest_sha256:
        raise ClosedFrontendError("backup manifest trust pin differs")
    manifest = json.loads(manifest_raw.decode("utf-8"))
    validate_manifest(manifest, root, expected_plan_id=plan_id)
    disk, _ = safe_file(root / "Caddyfile")
    active = json_value(safe_file(root / "caddy-active.json")[0], "backup Caddy active config")
    snippet_entry = manifest["artifacts"]["caddy_snippet"]
    snippet = safe_file(root / snippet_entry["filename"])[0] if snippet_entry["present"] else None
    return root, manifest, disk, active, snippet


def _write_exact(path: Path, raw: bytes) -> None:
    if os.path.lexists(path):
        current, _ = _current(path)
        if current != raw:
            raise ClosedFrontendError("closed frontend transaction artifact differs")
        return
    _atomic(path, raw, 0o600)


def apply_phase(backup: Path, transaction: Path, plan_id: str, manifest_sha256: str,
                caddyfile: Path, snippet_path: Path, hydro_domain: str,
                frontend_domain: str, upstream: str, admin: Admin | None = None) -> dict:
    _, _, baseline_disk, baseline_active, _ = _inputs(backup, plan_id, manifest_sha256)
    hydro_domain = _domain(hydro_domain, "Hydro domain")
    frontend_domain = _domain(frontend_domain, "frontend domain")
    if hydro_domain == frontend_domain:
        raise ClosedFrontendError("Hydro and frontend domains collide")
    upstream = _upstream(upstream)
    root = safe_directory(transaction)
    candidate = harden_caddyfile(baseline_disk, hydro_domain, snippet_path)
    closed = render_closed(frontend_domain, upstream)
    candidate_path = root / f"closed-frontend.{plan_id}.Caddyfile"
    closed_path = root / f"closed-frontend.{plan_id}.snippet"
    desired_path = root / f"closed-frontend.{plan_id}.active.json"
    _write_exact(candidate_path, candidate); _write_exact(closed_path, closed)
    live_disk, disk_mode = _current(caddyfile)
    if live_disk != baseline_disk:
        raise ClosedFrontendError("live Caddyfile differs from backup baseline")
    active_admin = admin or Admin()
    live, _ = get_live(active_admin)
    if caddy_canonical(live) != caddy_canonical(baseline_active):
        raise ClosedFrontendError("live Caddy config differs from backup baseline")
    if caddy_canonical(adapt(active_admin, baseline_disk)) != caddy_canonical(baseline_active):
        raise ClosedFrontendError("backup Caddy disk and active config differ")
    # The candidate imports the canonical snippet path.  On a clean install
    # that path does not exist yet, so Caddy cannot adapt the candidate until
    # the transaction-owned closed snippet has been durably published.  This
    # remains rollback-safe: rollback_phase accepts exactly ``closed`` here
    # and removes it when the clean baseline had no snippet.
    _atomic(snippet_path, closed, 0o644)
    desired = adapt(active_admin, candidate)
    _write_exact(desired_path, caddy_canonical(desired) + b"\n")
    _atomic(caddyfile, candidate, disk_mode)
    result = commit(active_admin, baseline_active, desired,
                    reread_disk=lambda: _current(caddyfile)[0],
                    expected_disk_sha256=hashlib.sha256(candidate).hexdigest())
    if _current(snippet_path)[0] != closed or _current(caddyfile)[0] != candidate:
        raise ClosedFrontendError("closed frontend disk verification differs")
    return {"status": "verified", "plan_id": plan_id, "closed": True,
            "hydro_route_hardened": True, "etag_used": result["etag_used"],
            "active_sha256": result["active_sha256"], "other_service_mutations": 0}


def rollback_phase(backup: Path, transaction: Path, plan_id: str, manifest_sha256: str,
                   caddyfile: Path, snippet_path: Path, admin: Admin | None = None) -> dict:
    root, manifest, baseline_disk, baseline_active, baseline_snippet = _inputs(
        backup, plan_id, manifest_sha256)
    tx = safe_directory(transaction)
    desired_path = tx / f"closed-frontend.{plan_id}.active.json"
    active_admin = admin or Admin()
    changed = False
    current_disk, _ = _current(caddyfile)
    current_snippet_row = _optional_current(snippet_path)
    current_snippet = current_snippet_row[0] if current_snippet_row is not None else None
    candidate_path = tx / f"closed-frontend.{plan_id}.Caddyfile"
    closed_path = tx / f"closed-frontend.{plan_id}.snippet"
    allowed_disk = {baseline_disk}
    allowed_snippet = {baseline_snippet}
    if os.path.lexists(candidate_path): allowed_disk.add(_current(candidate_path)[0])
    if os.path.lexists(closed_path): allowed_snippet.add(_current(closed_path)[0])
    if current_disk not in allowed_disk or current_snippet not in allowed_snippet:
        raise ClosedFrontendError("frontend disk state changed outside this transaction")
    disk_mode = manifest["artifacts"]["caddyfile"]["mode"]
    snippet_mode = manifest["artifacts"]["caddy_snippet"]["mode"]
    if current_disk != baseline_disk:
        _atomic(caddyfile, baseline_disk, disk_mode); changed = True
    if current_snippet != baseline_snippet:
        if baseline_snippet is None:
            closed = _current(closed_path)[0] if os.path.lexists(closed_path) else b""
            _remove_exact(snippet_path, closed); changed = True
        else:
            _atomic(snippet_path, baseline_snippet, snippet_mode); changed = True
    if os.path.lexists(desired_path):
        desired = json_value(_current(desired_path)[0], "desired Caddy active config")
        result = restore(active_admin, desired, baseline_active)
        changed = changed or not result["already_restored"]
    else:
        live, _ = get_live(active_admin)
        if caddy_canonical(live) != caddy_canonical(baseline_active):
            raise ClosedFrontendError("uncertain frontend apply changed active Caddy without evidence")
    live, _ = get_live(active_admin)
    if caddy_canonical(live) != caddy_canonical(baseline_active) \
            or _current(caddyfile)[0] != baseline_disk \
            or ((_optional_current(snippet_path) or (None, None))[0] != baseline_snippet):
        raise ClosedFrontendError("closed frontend rollback verification differs")
    return {"status": "rollback_verified", "plan_id": plan_id,
            "backup_manifest_sha256": manifest_sha256, "changed": changed,
            "other_service_mutations": 0}


def main() -> int:
    parser = argparse.ArgumentParser(); mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true"); mode.add_argument("--rollback", action="store_true")
    parser.add_argument("--backup-directory", required=True, type=Path)
    parser.add_argument("--transaction-directory", required=True, type=Path)
    parser.add_argument("--plan-id", required=True); parser.add_argument("--backup-manifest-sha256", required=True)
    parser.add_argument("--caddyfile", required=True, type=Path); parser.add_argument("--snippet", required=True, type=Path)
    parser.add_argument("--hydro-domain"); parser.add_argument("--frontend-domain"); parser.add_argument("--orchestrator-upstream")
    args = parser.parse_args()
    try:
        if platform.system().lower() != "linux" or os.geteuid() != 0 \
                or not HEX64.fullmatch(args.plan_id) or not HEX64.fullmatch(args.backup_manifest_sha256):
            raise ClosedFrontendError("closed frontend phase requires pinned Linux root")
        if args.apply:
            if None in (args.hydro_domain, args.frontend_domain, args.orchestrator_upstream):
                raise ClosedFrontendError("closed frontend apply arguments differ")
            result = apply_phase(args.backup_directory, args.transaction_directory, args.plan_id,
                                 args.backup_manifest_sha256, args.caddyfile, args.snippet,
                                 args.hydro_domain, args.frontend_domain, args.orchestrator_upstream)
        else:
            if any(value is not None for value in (args.hydro_domain, args.frontend_domain, args.orchestrator_upstream)):
                raise ClosedFrontendError("closed frontend rollback arguments differ")
            result = rollback_phase(args.backup_directory, args.transaction_directory, args.plan_id,
                                    args.backup_manifest_sha256, args.caddyfile, args.snippet)
        print(json.dumps(result, sort_keys=True)); return 0
    except (ClosedFrontendError, CaddyCommitError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"NO_GO: {exc}", file=sys.stderr); return 2


if __name__ == "__main__":
    raise SystemExit(main())
